### ISSUE TITLE
感谢大佬，非常棒的看图软件，如果可以更新就好了

### ISSUE THREAD

**Issue by warmplay** [hanFengSan/eHunter_local#3]
感谢大佬，非常棒的看图软件，希望能更新，eHunter的在线版本有些新功能十分好用，可惜本地图用不了

**Comment by hanFengSan** [comment]
明天更新

warmplay <notifications@github.com> 于 2020年4月11日周六 15:54写道：

**Comment by hanFengSan** [comment]
更新了, 你可以到下面两个地方下载:
https://yun.baidu.com/s/1wEnBe9uGoBKzNd4DCfbuAg 提取码:czft
https://github.com/hanFengSan/eHunter_local/releases
